(() => {
  "use strict";
  const defaults = { items: [], movements: [], opname: [], waste: [], settings: { default_min_stock: 5, valuation_method: "average", sync_enabled: true } };
  let userId = "anonymous";
  let data = structuredClone(defaults);
  const key = () => `biya_inventory_v2:${userId}`;
  const id = (prefix) => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
  const now = () => new Date().toISOString();
  function load(idValue) { userId = idValue || "anonymous"; try { data = { ...structuredClone(defaults), ...JSON.parse(localStorage.getItem(key()) || "{}") }; data.settings = { ...defaults.settings, ...(data.settings || {}) }; } catch { data = structuredClone(defaults); } return data; }
  function save() { localStorage.setItem(key(), JSON.stringify(data)); window.dispatchEvent(new CustomEvent("biya:inventory-updated")); }
  function item(itemId) { return data.items.find((entry) => String(entry.id) === String(itemId)); }
  function upsertItem(payload) { const current = payload.id ? item(payload.id) : null; const record = { id: payload.id || id("item"), code: payload.code || `INV-${Date.now().toString().slice(-6)}`, name: payload.name, category: payload.category || "Bahan Baku", unit: payload.unit || "unit", unit_price: Number(payload.unit_price) || 0, current_stock: Number(payload.current_stock) || 0, minimum_stock: Number(payload.minimum_stock ?? data.settings.default_min_stock) || 0, raw_material_id: payload.raw_material_id || null, source: payload.source || "inventory", updated_at: now(), created_at: payload.created_at || now() }; if (current) Object.assign(current, record); else data.items.unshift(record); save(); return record; }
  function addMovement(payload) { const target = item(payload.item_id); if (!target) throw new Error("Item tidak ditemukan."); const quantity = Number(payload.quantity) || 0; const delta = Number(payload.delta ?? quantity); const next = Number(target.current_stock) + delta; if (next < 0) throw new Error("Stok tidak mencukupi."); target.current_stock = next; if (payload.unit_price !== undefined && Number(payload.unit_price) >= 0 && delta > 0) { const oldValue = (next - delta) * Number(target.unit_price); target.unit_price = next ? (oldValue + delta * Number(payload.unit_price)) / next : Number(payload.unit_price); } const movement = { id: id("move"), date: payload.date, reference: payload.reference || `MOV-${Date.now()}`, item_id: target.id, item_name: target.name, type: payload.type, quantity, delta, balance: next, unit: target.unit, unit_price: target.unit_price, notes: payload.notes || "", reason: payload.reason || "", created_at: now() }; data.movements.unshift(movement); save(); return movement; }
  function stockIn(payload) { return addMovement({ ...payload, type: "stock_in", delta: Math.abs(Number(payload.quantity)) }); }
  function recordWaste(payload) { const target = item(payload.item_id); const movement = addMovement({ ...payload, type: "waste", delta: -Math.abs(Number(payload.quantity)) }); data.waste.unshift({ ...movement, reason: payload.reason, loss: Math.abs(Number(payload.quantity)) * Number(target.unit_price) }); save(); return movement; }
  function recordOpname(payload) { const target = item(payload.item_id); if (!target) throw new Error("Item tidak ditemukan."); const system = Number(target.current_stock), actual = Number(payload.actual), difference = actual - system; const movement = addMovement({ item_id: target.id, date: payload.date, quantity: difference, delta: difference, type: "opname", reference: `OPN-${Date.now()}`, notes: payload.notes || "Adjustment otomatis dari stock opname" }); data.opname.unshift({ id: id("opname"), date: payload.date, item_id: target.id, item_name: target.name, system, actual, difference, value: difference * Number(target.unit_price), movement_id: movement.id }); save(); return movement; }
  function removeItem(itemId) { data.items = data.items.filter((entry) => String(entry.id) !== String(itemId)); save(); }
  function updateSettings(settings) { data.settings = { ...data.settings, ...settings }; save(); }
  window.BIYAInventoryService = { load, getData: () => data, item, upsertItem, removeItem, stockIn, recordWaste, recordOpname, updateSettings };
})();
