(() => {
  "use strict";
  const defaults = { items: [], movements: [], opname: [], waste: [], settings: { default_min_stock: 5, valuation_method: "average", sync_enabled: true } };
  let userId = "anonymous";
  let client = null;
  let data = structuredClone(defaults);
  const id = (prefix) => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
  const randomCode = () => Math.random().toString(36).slice(2, 8).toUpperCase().padEnd(6, "0");
  const stockCode = () => `STK-${Date.now()}-${randomCode()}`;
  const now = () => new Date().toISOString();
  const numberValue = (value, fallback = 0) => Number(value ?? fallback) || 0;
  const notify = () => window.dispatchEvent(new CustomEvent("biya:inventory-updated"));
  const requireClient = () => { if (!client) throw new Error("Koneksi Supabase belum tersedia."); };
  function normalizeItem(row) { return { id: row.id, code: row.code, name: row.name, category: row.category || "Bahan Baku", supplier: row.supplier || "", purchase_qty: numberValue(row.purchase_qty), purchase_unit: row.purchase_unit || "Kg", purchase_price: numberValue(row.purchase_price), conversion_qty: numberValue(row.conversion_qty), waste: numberValue(row.waste), unit: row.unit || "unit", unit_price: numberValue(row.unit_price), current_stock: numberValue(row.current_stock), minimum_stock: numberValue(row.minimum_stock), raw_material_id: row.raw_material_id || null, raw_material_code: row.raw_material_code || null, source: row.source || "inventory", created_at: row.created_at, updated_at: row.updated_at }; }
  function normalizeMovement(row) { return { id: row.id, date: row.date, reference: row.reference, item_id: row.item_id, item_name: row.item_name, type: row.type, quantity: numberValue(row.quantity), delta: numberValue(row.delta), balance: numberValue(row.balance), unit: row.unit || "unit", unit_price: numberValue(row.unit_price), notes: row.notes || "", reason: row.reason || "", created_at: row.created_at }; }
  function itemToRow(item) { return { ...item, user_id: userId }; }
  function movementToRow(movement) { return { ...movement, user_id: userId }; }
  async function selectTable(table, columns = "*") { const { data: rows, error } = await client.from(table).select(columns).eq("user_id", userId); if (error) throw error; return rows || []; }
  async function load(idValue) { userId = idValue || "anonymous"; client = window.BiyaAuth?.client || null; data = structuredClone(defaults); requireClient(); const [items, movements] = await Promise.all([selectTable("inventory_stock_items"), selectTable("inventory_stock_movements")]); data.items = items.map(normalizeItem).sort((a, b) => String(b.created_at || "").localeCompare(String(a.created_at || ""))); data.movements = movements.map(normalizeMovement).sort((a, b) => String(b.date || "").localeCompare(String(a.date || "")) || String(b.created_at || "").localeCompare(String(a.created_at || ""))); data.waste = data.movements.filter((m) => m.type === "waste").map((m) => ({ ...m, loss: Math.abs(m.quantity) * Number(m.unit_price) })); data.opname = data.movements.filter((m) => m.type === "opname").map((m) => ({ ...m, system: Number(m.balance) - Number(m.delta), actual: Number(m.balance), difference: Number(m.delta), value: Number(m.delta) * Number(m.unit_price), movement_id: m.id })); return data; }
  function item(itemId) { return data.items.find((entry) => String(entry.id) === String(itemId)); }
  function calculateUnitPrice(payload, current) { const directUnitPrice = payload.unit_price ?? current?.unit_price; if (directUnitPrice !== undefined && directUnitPrice !== null && directUnitPrice !== "") return numberValue(directUnitPrice); const purchasePrice = numberValue(payload.purchase_price, current?.purchase_price); const conversionQty = numberValue(payload.conversion_qty, current?.conversion_qty); return conversionQty ? purchasePrice / conversionQty : 0; }
  async function upsertItem(payload) { requireClient(); const current = payload.id ? item(payload.id) : null; const isLegacyRawCode = current?.code && current.code === payload.raw_material_code && current.code.startsWith("RAW-"); const record = { id: payload.id || id("item"), code: (!isLegacyRawCode && current?.code) || payload.code || stockCode(), name: payload.name, category: payload.category || "Bahan Baku", supplier: payload.supplier ?? current?.supplier ?? "", purchase_qty: numberValue(payload.purchase_qty, current?.purchase_qty), purchase_unit: payload.purchase_unit ?? current?.purchase_unit ?? "Kg", purchase_price: numberValue(payload.purchase_price, current?.purchase_price), conversion_qty: numberValue(payload.conversion_qty, current?.conversion_qty), waste: numberValue(payload.waste, current?.waste), unit: payload.unit || current?.unit || "unit", unit_price: calculateUnitPrice(payload, current), current_stock: numberValue(payload.current_stock, current?.current_stock), minimum_stock: numberValue(payload.minimum_stock, current?.minimum_stock ?? data.settings.default_min_stock), raw_material_id: payload.raw_material_id || current?.raw_material_id || null, raw_material_code: payload.raw_material_code || current?.raw_material_code || null, source: payload.source || current?.source || "inventory", updated_at: now(), created_at: payload.created_at || current?.created_at || now() };
    const query = current ? client.from("inventory_stock_items").update(itemToRow(record)).eq("id", record.id).eq("user_id", userId) : client.from("inventory_stock_items").insert(itemToRow(record));
    const { data: saved, error } = await query.select("*").single(); if (error) throw error; const normalized = normalizeItem(saved); if (current) Object.assign(current, normalized); else data.items.unshift(normalized); notify(); return normalized; }
  async function persistItemStock(target) { const { error } = await client.from("inventory_stock_items").update({ current_stock: target.current_stock, unit_price: target.unit_price, updated_at: now() }).eq("id", target.id).eq("user_id", userId); if (error) throw error; }
  async function addMovement(payload) { requireClient(); const target = item(payload.item_id); if (!target) throw new Error("Item tidak ditemukan."); const quantity = Math.abs(Number(payload.quantity) || 0); const delta = Number(payload.delta ?? quantity); const next = Number(target.current_stock) + delta; if (next < 0) throw new Error("Stok tidak mencukupi."); target.current_stock = next; if (payload.unit_price !== undefined && Number(payload.unit_price) >= 0 && delta > 0) { const oldValue = (next - delta) * Number(target.unit_price); target.unit_price = next ? (oldValue + delta * Number(payload.unit_price)) / next : Number(payload.unit_price); } const movement = { id: id("move"), date: payload.date, reference: payload.reference || `MOV-${Date.now()}`, item_id: target.id, item_name: target.name, type: payload.type, quantity, delta, balance: next, unit: target.unit, unit_price: target.unit_price, notes: payload.notes || "", reason: payload.reason || "", created_at: now() }; await persistItemStock(target); const { data: saved, error } = await client.from("inventory_stock_movements").insert(movementToRow(movement)).select("*").single(); if (error) throw error; const normalized = normalizeMovement(saved); data.movements.unshift(normalized); if (normalized.type === "waste") data.waste.unshift({ ...normalized, loss: Math.abs(normalized.quantity) * Number(normalized.unit_price) }); notify(); return normalized; }
  const stockIn = (payload) => addMovement({ ...payload, type: "stock_in", delta: Math.abs(Number(payload.quantity)) });
  async function recordWaste(payload) { return addMovement({ ...payload, type: "waste", delta: -Math.abs(Number(payload.quantity)) }); }
  async function recordOpname(payload) { const target = item(payload.item_id); if (!target) throw new Error("Item tidak ditemukan."); const system = Number(target.current_stock), actual = Number(payload.actual), difference = actual - system; const movement = await addMovement({ item_id: target.id, date: payload.date, quantity: Math.abs(difference), delta: difference, type: "opname", reference: `OPN-${Date.now()}`, notes: payload.notes || "Adjustment otomatis dari stock opname" }); data.opname.unshift({ id: id("opname"), date: payload.date, item_id: target.id, item_name: target.name, system, actual, difference, value: difference * Number(target.unit_price), movement_id: movement.id }); return movement; }
  async function removeItem(itemId) { requireClient(); const { error } = await client.from("inventory_stock_items").delete().eq("id", itemId).eq("user_id", userId); if (error) throw error; data.items = data.items.filter((entry) => String(entry.id) !== String(itemId)); notify(); }
  function updateSettings(settings) { data.settings = { ...data.settings, ...settings }; notify(); }
  window.BIYAInventoryService = { load, getData: () => data, item, upsertItem, removeItem, stockIn, recordWaste, recordOpname, updateSettings };
})();
