-- BIYA Inventory core tables, atomic stock operations, and private developer RLS.
begin;
create extension if not exists pgcrypto;
create table if not exists public.inventory_items (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,item_code text not null,name text not null,source_type text not null default 'inventory_only' check(source_type in('raw_material','inventory_only')),raw_material_id text null,category text not null,subcategory text,base_unit text not null,unit_price numeric(18,4) not null default 0 check(unit_price>=0),minimum_stock numeric(18,4) not null default 0 check(minimum_stock>=0),current_stock numeric(18,4) not null default 0,supplier text,status text not null default 'active' check(status in('active','inactive')),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(user_id,item_code),unique(user_id,raw_material_id));
create table if not exists public.inventory_movements (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,transaction_no text not null,movement_type text not null,item_id uuid not null references public.inventory_items(id) on delete restrict,item_name text not null,category text,quantity numeric(18,4) not null,unit text not null,unit_price numeric(18,4) not null default 0,total_value numeric(18,4) not null default 0,location text,notes text,pic text,date date not null default current_date,created_at timestamptz not null default now(),unique(user_id,transaction_no));
create table if not exists public.inventory_waste (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,item_id uuid not null references public.inventory_items(id) on delete restrict,item_name text not null,category text,quantity numeric(18,4) not null check(quantity>0),unit text not null,unit_price numeric(18,4) not null default 0,total_loss numeric(18,4) not null default 0,waste_type text not null,reason text,notes text,pic text,date date not null default current_date,created_at timestamptz not null default now());
create table if not exists public.inventory_opname (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,item_id uuid not null references public.inventory_items(id) on delete restrict,item_name text not null,system_stock numeric(18,4) not null,actual_stock numeric(18,4) not null,difference numeric(18,4) not null,difference_value numeric(18,4) not null default 0,status text not null,adjustment_applied boolean not null default false,notes text,pic text,date date not null default current_date,created_at timestamptz not null default now());
create table if not exists public.inventory_settings (id uuid primary key default gen_random_uuid(),user_id uuid not null unique references auth.users(id) on delete cascade,default_min_stock numeric(18,4) not null default 5,allow_negative_stock boolean not null default false,auto_sync_raw_material boolean not null default true,auto_create_inventory_item boolean not null default false,valuation_method text not null default 'average_cost',waste_reasons jsonb not null default '["Expired","Rusak","Tumpah","Salah Produksi","Reject","Other"]'::jsonb,movement_types jsonb not null default '["stock_in","stock_out","transfer","adjustment","return","usage_production"]'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists inventory_items_user_status_idx on public.inventory_items(user_id,status);create index if not exists inventory_movements_user_date_idx on public.inventory_movements(user_id,date desc);create index if not exists inventory_waste_user_date_idx on public.inventory_waste(user_id,date desc);create index if not exists inventory_opname_user_date_idx on public.inventory_opname(user_id,date desc);
DO $policies$ DECLARE t text; p record; BEGIN FOREACH t IN ARRAY ARRAY['inventory_items','inventory_movements','inventory_waste','inventory_opname','inventory_settings'] LOOP EXECUTE format('alter table public.%I enable row level security',t);EXECUTE format('alter table public.%I force row level security',t);FOR p IN SELECT policyname from pg_policies where schemaname='public' and tablename=t LOOP EXECUTE format('drop policy if exists %I on public.%I',p.policyname,t);END LOOP;EXECUTE format('create policy %I on public.%I for all to authenticated using (user_id=auth.uid() and public.biya_inventory_access_allowed()) with check (user_id=auth.uid() and public.biya_inventory_access_allowed())','Inventory owner developer access',t);EXECUTE format('revoke all on public.%I from anon',t);EXECUTE format('grant select,insert,update,delete on public.%I to authenticated',t);END LOOP;END $policies$;
commit;
